###################
# Run APSIM Tests #
###################

FROM microsoft/dotnet-framework-build:4.7.1
SHELL ["powershell", "-Command"]

# Install Chocolatey. This is a package installer for Windows.
RUN Install-PackageProvider -Name Chocolatey -Force;																		\
	Install-Package         -Name SlikSVN               -Force -RequiredVersion 1.8.5.20140421;

# Configure Chocolatey, and use it to install Visual C++ 2017 Runtime.
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex; 		\
    choco feature disable –name showDownloadProgress;                                        								\
	choco feature enable -n allowGlobalConfirmation;                                         								\
    choco install vcredist2017;

COPY runTests.bat /runTests.bat

ENTRYPOINT ["runtests.bat"]