pipeline {
    agent none
    stages {
        stage('BuildAndRun') {
			agent {
				label "windows && docker && heavyweight"
			}
			
			environment {
				BUILD_PSW = credentials('builds-classic-password')
				DB_CONN_PSW = credentials('db-connect-password')
				APSIM_CREDS = credentials('apsim-site-creds')
			}
			steps {
				bat '''
					@echo off
					if not exist Docker (
						git clone https://github.com/APSIMInitiative/Docker Docker
					)
					pushd Docker
					git clean -xfdq
					git reset .
					git checkout .
					git checkout master
					git pull
					popd
					call Docker\\OldApsim\\Release\\createRelease.bat
				'''
			}
        }
    }
}
