pipeline {
    agent none
    stages {
        stage('BuildAndRun') {
			agent {
					label "windows && docker && heavyweight"
			}
			
			environment {
				BOB_CREDS = credentials('bob')
			}
			steps {
				bat '''
					@echo off
					if not exist Docker (
						git clone https://github.com/APSIMInitiative/Docker Docker
					)
					pushd Docker
					git clean -xfdq
					git reset .
					git checkout .
					git checkout master
					git pull
					popd
					copy /y C:\\new-code-signer.pfx Docker\\OldApsim\\Compile\\
					docker build -m 12g -t buildapsim %cd%\\Docker\\OldApsim\\Compile
					if errorlevel 1 (
						echo Encountered an error while building docker container. Exiting...
						exit 1
					)
					docker run -m 12g -e "sha1=%ghprbActualCommit%" -e BOB_CREDS buildapsim
				'''
			}
        }
    }
}
